name: GitHub Actions Demo
on: [push]
env:
  LANG: "en_US.UTF-8"
  LANGUAGE: "en_US:en"
  LC_ALL: "en_US.UTF-8"

jobs:
  Explore-GitHub-Actions:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - run: set
      - run: cs3030actions
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by me!"

